name: "Code Review Action"
description: "Automatically reviews PRs using an external Ollama API"
author: "ljy2855"
inputs:
  github_token:
    description: "GitHub token to authenticate API requests"
    required: true
  github_owner:
    description: "The repository owner"
    required: true
  github_repository:
    description: "The repository name"
    required: true
  pr_number:
    description: "The pull request number"
    required: true
  ollama_api_url:
    description: "The base URL of the Ollama API"
    required: true
  ollama_model:
    description: "LLM model to generate the review comment"
    required: true
  prompt:
    description: "The prompt to generate the review comment"
    required: false
    default: "Review this code:"

runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "python3"
  args:
    - "/app/main.py"
  
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_OWNER: ${{ inputs.github_owner }}
    GITHUB_REPOSITORY: ${{ inputs.github_repository }}
    PR_NUMBER: ${{ inputs.pr_number }}
    OLLAMA_API_URL: ${{ inputs.ollama_api_url }}
    OLLAMA_MODEL: ${{ inputs.ollama_model }}
    PROMPT: ${{ inputs.prompt }}

branding:
  icon: "code"
  color: "blue"
