name: 'LLM Code Review Action'
description: 'Automatically reviews PRs using an external Ollama API'
author: 'ljy2855'
inputs:
  github_token:
    description: 'The GitHub token'
    required: true
  github_owner:
    description: 'The repository owner'
    required: true
  github_repository:
    description: 'The repository name'
    required: true
  pr_number:
    description: 'The pull request number'
    required: true
  pr_title:
    description: 'The pull request title'
    required: true
  pr_body:
    description: 'The pull request body'
    required: true
  ollama_api_url:
    description: 'The base URL of the Ollama API'
    required: true
  ollama_model:
    description: 'LLM model to generate the review comment'
    required: true
  prompt_type:
    description: 'The type of prompt to generate the review comment'
    required: false
    default: 'GENERAL_REVIEW'
  prompt_language:
    description: 'The language of the prompt to generate the review comment'
    required: false
    default: 'EN'

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: 'python3'
  args:
    - '/app/src/main.py'

  env:
    GITHUB_OWNER: ${{ inputs.github_owner }}
    GITHUB_REPOSITORY: ${{ inputs.github_repository }}
    PR_NUMBER: ${{ inputs.pr_number }}
    PR_TITLE: ${{ inputs.pr_title }}
    PR_BODY: ${{ inputs.pr_body }}
    OLLAMA_API_URL: ${{ inputs.ollama_api_url }}
    OLLAMA_MODEL: ${{ inputs.ollama_model }}
    PROMPT_TYPE: ${{ inputs.prompt_type }}
    PROMPT_LANGUAGE: ${{ inputs.prompt_language }}
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

branding:
  icon: 'code'
  color: 'blue'
