# Python 3.12 slim 이미지 사용
FROM python:3.12-slim

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 패키지 설치
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# 소스 코드 및 테스트 코드 복사
COPY src/ ./src
COPY tests/ ./tests

# 환경 변수 설정 (필요한 경우)
ENV PATH="/usr/local/bin:${PATH}"

# 환경 변수 설정 (PYTHONPATH 설정)
ENV PYTHONPATH="${PYTHONPATH}:/app/src"

# 테스트 실행을 위한 기본 명령어 설정
CMD ["python3", "-m", "unittest", "discover", "-s", "tests", "-p", "test_*.py"]
