name: 'Test Container Action'

on:
  pull_request:
    types: [opened]

permissions:
  contents: read # 콘텐츠 접근 권한 (리포지토리 파일 읽기)
  pull-requests: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }} # PR에서 체크아웃할 브랜치를 명확히 지정

      - name: Run Container Action
        uses: ljy2855/llm-code-reviewer@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_owner: ${{ github.repository_owner }}
          github_repository: ${{ github.repository }}
          pr_number: ${{ github.event.pull_request.number }}
          pr_title: ${{ github.event.pull_request.title }}
          pr_body: ${{ github.event.pull_request.body }}
          ollama_api_url: ${{ secrets.OLLAMA_API_URL }}
          ollama_model: 'llama3.1:8b'
          prompt_type: 'GENERAL_REVIEW'
          prompt_language: 'KR'
